version: "3.8"

services:
  frontend:
    image: frontend
    container_name: client-app
    ports:
      - "3011:3000"
    restart: always
    depends_on:
      - backend
    networks:
      - spring-react

  backend:
    image: backend
    container_name: server-app
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - server-db
      - spring-react

  mysqldb:
    image: mysql
    container_name: database
    ports:
      - "3009:3006"
    restart: always
    environment:
      MYSQL_DATABASE: teaching_institution_management_system
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PORT: 3006
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "database"]
      timeout: 17s
      retries: 3
    networks:
      - server-db
networks:
  server-db:
    external: true
    driver: bridge
  spring-react:
    external: true
    driver: bridge
